---

- name: Install RPM package.
  yum:
    name: "https://downloads.nessus.org/nessus3dl.php?file=NessusAgent-{{ nessus_version }}-es{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm&licence_accept=yes&t={{ nessus_timecheck }}"
    state: present
