---

# Bypass download automation prevention
- name: Load Nessus Agent download page.
  local_action:
    module: get_url
    url: "{{ nessus_download_page }}"
    dest: "/tmp/nessus_download.html"
    force: yes

- name: Remove line with invalid og:description.
  local_action:
    module: lineinfile
    path: "/tmp/nessus_download.html"
    regexp: 'meta.+\w+:description'
    state: absent

- name: Grep timecheck line and make a single line file with it.
  local_action:
    module: shell grep timecheck /tmp/nessus_download.html > /tmp/timecheck.html

- name: Grep for timecheck variable.
  local_action:
    module: xml
    path: "/tmp/timecheck.html"
    xpath: '//*[@id="timecheck"]'
    content: text
  register: nessus_timecheck

- debug:
    var: nessus_timecheck
    verbosity: 0

- name: Cleanup local tmp download.
  local_action:
    module: file
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/nessus_download.html"
    - "/tmp/timecheck.html"
    - "{{ nessus_tmpdir }}"
