---

# Bypass download automation prevention
- name: Load Nessus Agent download page.
  local_action:
    module: get_url
    url: "{{ nessus_download_page }}"
    dest: "/tmp/nessus_download.html"
    force: yes

- name: Remove line with invalid og:description.
  lineinfile:
    path: "/tmp/nessus_download.html"
    regexp: 'og:description'
    state: absent

- name: Grep for timecheck variable.
  local_action:
    module: xml
    path: "/tmp/nessus_download.html"
    xpath: '//*[@id="timecheck"]'
    content: text
  register: nessus_timecheck

- debug:
    var: nessus_timecheck
    verbosity: 0

- name: Cleanup local tmp download.
  local_action:
    module: file
    path: "/tmp/nessus_download.html"
    state: absent

- name: Cleanup temp dir.
  local_action:
    module: file
    path: "{{ nessus_tmpdir }}"
    state: absent
