---

- name: Install Ubuntu package.
  apt:
    deb: "https://downloads.nessus.org/nessus3dl.php?file=NessusAgent-{{ nessus_version }}-ubuntu1110_amd64.deb&licence_accept=yes&t={{ nessus_timecheck }}"
    state: present
