---

- set_fact:
    nessus_ubuntu_architecture: "{{ ansible_architecture == 'x86_64' | ternary('amd64','i386') }}"

# Someday add the checksum to this.
# Remote machines may not have Internet access. Assume Ansible box does.
- name: Download deb package to local tmp.
  local_action:
    module: get_url
    url: "https://downloads.nessus.org/nessus3dl.php?file=NessusAgent-{{ nessus_version }}-ubuntu1110_{{ nessus_ubuntu_architecture }}.deb&licence_accept=yes&t={{ nessus_timecheck }}"
    dest: "{{ local_tmp }}/NessusAgent-{{ nessus_version }}-ubuntu1110_{{ nessus_ubuntu_architecture }}.deb"
    force: no

# Copy would support a URL, but doing get_url without force works like a cache.
- name: Upload deb to remote.
  copy:
    src: "{{ local_tmp }}/NessusAgent-{{ nessus_version }}-ubuntu1110_{{ nessus_ubuntu_architecture }}.deb"
    dest: "{{ nessus_linux_tmp }}/NessusAgent-{{ nessus_version }}-ubuntu1110_{{ nessus_ubuntu_architecture }}.deb"
    force: no

- name: Install Ubuntu package.
  apt:
    deb: "{{ nessus_linux_tmp }}/NessusAgent-{{ nessus_version }}-ubuntu1110_{{ nessus_ubuntu_architecture }}.deb"
    state: present
