---

- name: Check for existing Nessus Agent installation.
  win_stat:
    path: "C:\\Program Files\\Tenable\\Nessus Agent"
  register: nessus_installed

- debug:
    var: nessus_installed
    verbosity: 1

# Skip all the download, copy, and install stuff if the files already exist.
- block:

  - set_fact:
      nessus_windows_architecture: "{{ (ansible_architecture == '64-bit') | ternary('x64','Win32') }}"

  - set_fact:
      data_file_name: "NessusAgent-{{ nessus_version }}-{{ nessus_windows_architecture }}.msi"

  - import_tasks: data_download_id.yml

  # https://docs.tenable.com/nessus/Content/InstallNessusAgentWindows.htm
  - name: Install MSI package.
    win_package:
      path: "https://tenable-downloads-production.s3.amazonaws.com/uploads/download/file/{{ nessus_download_id.stdout }}/{{ data_file_name }}"
      arguments:
        - "NESSUS_GROUPS=\"{{ nessus_agent_group }}\""
        - "NESSUS_SERVER=\"{{ nessus_agent_host }}\""
        - "NESSUS_KEY={{ nessus_agent_key }}"
        - /qn
      creates_path: "C:\\Program Files\\Tenable\\Nessus Agent"
      creates_service: "Tenable Nessus Agent"
      state: present
    become: yes
    ignore_errors: "{{ ansible_check_mode }}"

  when: not nessus_installed.stat.exists
