---

- name: restart nessusagent
  service:
    name: nessusagent
    state: restarted
  when: ansible_system == "Linux"

- name: restart Tenable Nessus Agent
  win_service:
    name: Tenable Nessus Agent
    state: restarted
  when: ansible_os_family == "Windows"
